--- 根据id查询redis中的记录
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huang.
--- DateTime: 16/09/2023 14:48
---
ngx.header.content_type = "application/json;charset=utf8"
-- 获取请求头参数中的id
local uri_args = ngx.req.get_uri_args()
local id = uri_args["id"]

-- 引入redis库
local redis = require("resty.redis")
-- 创建redis对象
local red = redis:new()
-- 超时时间
red:set_timeout(2000)
-- 连接
local ok, err = red:connect("192.168.220.110", 6379)
-- 获取key值
local res_content = red:get("content_" .. id)
-- 输出到返回响应中
ngx.say(res_content)
-- 关闭连接
red:close()