---
---读取所有三级分类信息
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huang.
--- DateTime: 16/09/2023 18:35

ngx.header.content_type = "application/json;charset=utf-8"

--nginx 缓存 nginx.conf 可以配置字典名dis_cache_hh
local cache_ngx = ngx.shared.dis_cache_hh;
local content_cache = cache_ngx:get("cl");

if content_cache == "" or content_cache == nil then
    local redis = require("resty.redis");
    local red = redis:new();
    red:set_timeout(2000)
    red:connect("192.168.220.110", 6379);
    local res_content = red:get("cl")

    if ngx.null == res_content then
        local cjson = require("cjson");
        local mysql = require("resty.mysql");
        local db = mysql:new();
        db:set_timeout(2000);
        local props = {
            host = "192.168.220.110",
            port = 3306,
            database = "legou",
            user = "root",
            password = "root"
        }
        local res = db:connect(props);
        local select_sql = "select id_, is_parent_, order_, parent_id_, title_, expand_ from category_";
        res = db:query(select_sql);
        local response_json = cjson.encode(res);
        red:set("cl", response_json)
        ngx.say("mysql data: " .. response_json)
        db:close()
    else
        -- redis不为空
        cache_ngx:set("cl", res_content, 10 * 60)
        ngx.say("redis data: " .. res_content)
    end
    -- 不要忘记关闭
    red:close();
else
    -- nginx有数据
    ngx.say("nginx cache data :" .. content_cache)
end


--- 重定向到商品分类微服务来代替查询数据库
--return ngx.redirect("http://192.168.220.1:8062/api/item/category/list")