server:
  port: 9007

logging:
  # file: demo.log
  pattern:
    console: "%d - %msg%n"
  level:
    org.springframework.web: debug
    com.hh: debug

spring:
  redis:
    host: 192.168.220.110
    port: 6379

# canal 配置
canal:
  client:
    instances:
      # example
      example:
        host: 192.168.220.110
        port: 11111