server:
  port: 9010

logging:
  #  file: demo.log
  pattern:
    console: "%d - %msg%n"
  level:
    org.springframework.web: debug
    com.hh: debug

spring:
  rabbitmq:
    host: 192.168.220.110
    port: 5672

mq:
  pay:
    exchange:
      order: exchange.pay.order
    queue:
      order: queue.pay.order
    routing:
      key: routing.pay.order