server:
  port: 9006

logging:
  #  file: demo.log
  pattern:
    console: "%d - %msg%n"
  level:
    org.springframework.web: debug
    com.hh: debug

spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.220.110:9300
  elasticsearch:
    rest:
      uris: 192.168.220.110:9200

  jackson:
    # 配置json处理时忽略空值
    default-property-inclusion: non_null
