server:
  port: 9004
logging:
  #file: demo.log  #日志名
  pattern:
    console: "%d - %msg%n"
  level:
    org.springframework.web: debug
    com.hh: debug

#security:
#  oauth2:
#    resource:
#      jwt:
#        key-url: https://localhost:9898/oauth/token_key #如果使用jwt，可以获取公钥用于token的验签

spring:
  servlet:
    multipart:
      enabled: true
      # 允许上传大小
      max-file-size: 10MB
      max-request-size: 20MB

fdfs:
  # 链接超时
  connect-timeout: 60
  # 读取时间
  so-timeout: 60
  #  生成缩略图参数
  thumb-image:
    width: 150
    height: 150
  tracker-list: 192.168.220.110:22122